import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';
const client=createClient('https://reybalitebntwzkmujeo.supabase.co','sb_publishable_mz0eHqZgfIxoqAAx9hFCJg_3ZsKBJjb');
const CATS=[['coffee_rating','☕ Coffee'],['food_rating','🍰 Food & Pastries'],['atmosphere_rating','🪑 Atmosphere'],['value_rating','💰 Value'],['activities_rating','🎮 Activities'],['workability_rating','📚 Workability']];
let cafeId=null;
const $=s=>document.querySelector(s);
function cups(n){return '☕'.repeat(Number(n||0))+'·'.repeat(5-Number(n||0));}
function esc(s=''){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function ensureReviewUI(){
 if($('#v4-review-style'))return;
 const st=document.createElement('style');st.id='v4-review-style';st.textContent='.v4-review-summary{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:16px;margin:16px 0;border:1px solid #eadfd6;border-radius:16px;background:#fbf7f3}.v4-cup-score{font-size:1.4rem;font-weight:800;letter-spacing:1px}.v4-breakdown{display:grid;gap:8px;margin:10px 0 18px}.v4-breakdown-row{display:flex;justify-content:space-between;gap:12px;font-size:.92rem}.v4-review-card{padding:14px 0;border-top:1px solid #eee4dc}.v4-review-head{display:flex;justify-content:space-between;gap:10px}.v4-review-cats{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.v4-cat{padding:4px 8px;border-radius:999px;background:#f3ebe5;font-size:.8rem}.v4-review-note{white-space:pre-wrap;margin:8px 0 0}.v4-form-cats{display:grid;gap:10px}.v4-form-cat{display:flex;align-items:center;justify-content:space-between;gap:10px}.v4-form-cat select{min-width:120px}.v4-review-summary h3{margin:2px 0}.v4-review-empty{padding:10px 0}.v4-small{font-size:.82rem;color:#777}';document.head.appendChild(st);
 const profile=$('#view-dialog .cafe-profile'); if(!profile)return;
 const visit=profile.querySelector('.visits-section');
 const wrap=document.createElement('section');wrap.id='v4-review-area';wrap.innerHTML=`<section class="v4-review-summary"><div><span class="eyebrow">Kafé Cups</span><h3 id="v4-average">—</h3><span id="v4-count" class="muted">No reviews yet</span></div><button id="v4-add-review" type="button">☕ Review</button></section><div id="v4-breakdown" class="v4-breakdown"></div><section><div class="section-head"><div><span class="eyebrow">Experiences</span><h3>Reviews</h3></div></div><div id="v4-reviews-list"></div></section>`;
 profile.insertBefore(wrap,visit||null);
 $('#v4-add-review').addEventListener('click',openReviewForm);
}
function openReviewForm(){
 let d=$('#v4-review-dialog');if(!d){d=document.createElement('dialog');d.id='v4-review-dialog';d.innerHTML=`<form class="dialog-card" id="v4-review-form"><div class="dialog-head"><div><span class="eyebrow">Kafé Cups</span><h2>Share your experience</h2></div><button type="button" class="ghost icon-btn" id="v4-close-review">✕</button></div><p class="muted">Rate only what you actually experienced. Leave categories blank when they don't apply.</p><div class="v4-form-cats">${CATS.map(([id,label])=>`<div class="v4-form-cat"><label for="v4-${id}">${label}</label><select id="v4-${id}"><option value="">Not rated</option><option value="1">☕</option><option value="2">☕☕</option><option value="3">☕☕☕</option><option value="4">☕☕☕☕</option><option value="5">☕☕☕☕☕</option></select></div>`).join('')}</div><label>Your experience<textarea id="v4-note" rows="5" maxlength="2000" placeholder="What stood out about this café?"></textarea></label><div class="actions"><button type="submit">Save review</button></div><p id="v4-review-msg" class="message"></p></form>`;document.body.appendChild(d);$('#v4-close-review').onclick=()=>d.close();$('#v4-review-form').onsubmit=saveReview;}
 d.showModal();
}
async function saveReview(e){e.preventDefault();const{data:{user}}=await client.auth.getUser();if(!user||!cafeId)return;const payload={cafe_id:cafeId,user_id:user.id,note:$('#v4-note').value.trim()||null};let rated=false;CATS.forEach(([id])=>{const v=$(`#v4-${id}`).value;payload[id]=v?Number(v):null;if(v)rated=true});if(!rated){$('#v4-review-msg').textContent='Please rate at least one category.';return}const{error}=await client.from('cafe_reviews').upsert(payload,{onConflict:'cafe_id,user_id'});if(error){$('#v4-review-msg').textContent=error.message;return}$('#v4-review-dialog').close();await loadReviews();}
async function loadReviews(){if(!cafeId)return;ensureReviewUI();const{data,error}=await client.from('cafe_reviews').select('id,user_id,coffee_rating,food_rating,atmosphere_rating,value_rating,activities_rating,workability_rating,note,created_at,profiles(display_name)').eq('cafe_id',cafeId).order('created_at',{ascending:false});if(error){$('#v4-reviews-list').innerHTML=`<p class="message">${esc(error.message)}</p>`;return}const rows=data||[];const totals=CATS.map(([id,label])=>{const vals=rows.map(r=>r[id]).filter(v=>v!=null);return{id,label,avg:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,count:vals.length}});const all=rows.flatMap(r=>CATS.map(([id])=>r[id]).filter(v=>v!=null));const avg=all.length?all.reduce((a,b)=>a+b,0)/all.length:null;$('#v4-average').textContent=avg?`${cups(Math.round(avg))} ${avg.toFixed(1)} Cups`: 'No Cups yet';$('#v4-count').textContent=`${rows.length} review${rows.length===1?'':'s'}`;$('#v4-breakdown').innerHTML=totals.filter(x=>x.avg).map(x=>`<div class="v4-breakdown-row"><span>${x.label}</span><strong>${cups(Math.round(x.avg))} ${x.avg.toFixed(1)}</strong></div>`).join('');if(!rows.length){$('#v4-reviews-list').innerHTML='<p class="muted v4-review-empty">No reviews yet. Be the first to share an experience.</p>';return}$('#v4-reviews-list').innerHTML=rows.map(r=>{const name=esc(r.profiles?.display_name||'Local Kafé member');const date=new Date(r.created_at).toLocaleDateString();const cats=CATS.filter(([id])=>r[id]!=null).map(([id,label])=>`<span class="v4-cat">${label} ${cups(r[id])}</span>`).join('');return `<article class="v4-review-card"><div class="v4-review-head"><strong>${name}</strong><span class="v4-small">${date}</span></div><div class="v4-review-cats">${cats}</div>${r.note?`<p class="v4-review-note">${esc(r.note)}</p>`:''}</article>`}).join('');}
function hook(){if(typeof window.openCafeProfile!=='function'){setTimeout(hook,200);return}const original=window.openCafeProfile;window.openCafeProfile=async id=>{cafeId=id;await original(id);ensureReviewUI();await loadReviews()};}
hook();